packages:
  - apps/desktop
  - packages/**/*
  - apps/desktop/layer/*
  - "!**/example"
  - "!**/example/**"

catalog:
  "@follow-app/client-sdk": 0.3.92
  "@folo-services/ai-tools": 0.2.65
  tailwindcss-uikit-colors: 1.0.0
  typescript: 5.9.3

ignorePatchFailures: false

onlyBuiltDependencies:
  - "@tsslint/core"
  - "@tsslint/eslint"
  - bufferutil
  - core-js
  - dtrace-provider
  - electron
  - electron-winstaller
  - esbuild
  - fast-folder-size
  - fs-xattr
  - macos-alias
  - msedge-tts
  - protobufjs
  - sharp
  - simple-git-hooks
  - utf-8-validate

overrides:
  "@electron/node-gyp": 10.2.0-electron.2
  "@floating-ui/core": 1.7.2
  "@floating-ui/dom": 1.7.2
  "@floating-ui/react": 0.27.14
  "@floating-ui/react-dom": 2.1.4
  "@types/react": 19.1.17
  drizzle-orm: 0.45.1
  global-agent>serialize-error: 7.0.1
  is-core-module: npm:@nolyfill/is-core-module@1.0.39
  isarray: npm:@nolyfill/isarray@1.0.44
  react: 19.1.0
  react-dom: 19.1.0
  serialize-error: 2.1.0

patchedDependencies:
  "@microflash/remark-callout-directives": patches/@microflash__remark-callout-directives.patch
  "@mozilla/readability@0.6.0": patches/@mozilla__readability@0.6.0.patch
  "@pengx17/electron-forge-maker-appimage": patches/@pengx17__electron-forge-maker-appimage.patch
  re-resizable@6.11.2: patches/re-resizable@6.11.2.patch
  workbox-precaching: patches/workbox-precaching.patch
